### ISSUE TITLE
BeginScope() in MicrosoftExtensions.Logging.Xunit fails since netcore 3.0

### ISSUE THREAD

**Issue by springy76** [hcoona/OneDotNet#1]
because starting with netcore 3.0 there are no public types in `Microsoft.Extensions.Logging.Abstractions.Internal` namespace any more, all "pubinternal" types have been redeclared as "internal", like `NullScope`.

So at runtime you only get a `TypeLoadException` "Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3..."

**Comment by springy76** [comment]
You just would have to rewrite
```c#
    public IDisposable BeginScope<TState>(TState state) => NullScope.Instance;
```
into
```c#
    public IDisposable BeginScope<TState>(TState state) => NullLogger.Instance.BeginScope(state);
```

**Comment by hcoona** [comment]
Cool, thank you for figuring out it. I'm currently busy for some other works, so maintaining it slowly.
